[package]
name = "jupyter-keras-tract-tf1"
version = "0.1.0"
authors = ["Matthew Alhonte <mattalhonte@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
tract-core = { path="../../core" }
tract-tensorflow = { path = "../../tensorflow" }
